import pyautogui as gui
import time
def changeLanguage():
    gui.keyDown("alt")
    gui.keyDown("shift")
    gui.keyUp("alt")
    gui.keyUp("shift")
def browse(url):
    width,height = gui.size()
    UrlLine = (248,65)
    gui.moveTo(0,height-1)
    gui.click()
    time.sleep(0.1)
    gui.typewrite("Chrome")
    time.sleep(1)
    gui.click()
    gui.moveTo(UrlLine)
    time.sleep(0.2)
    gui.click()
    gui.doubleClick()
    gui.typewrite("https://mail.google.com")
    gui.typewrite(["enter"])
#browse("www.one.co.il")
#time.sleep(7.5)
for i in range(0,30):
    gui.moveTo(92,225)
    gui.click()
    time.sleep(0.2)
    gui.moveTo(865,270)
    gui.click()
    gui.typewrite("shaikimhi219@gmail.com")
    time.sleep(0.05)
    #gui.typewrite(["tab"])
    gui.click(865,315)
    gui.click(865,315)    
    #changeLanguage()
    gui.typewrite("hello"+str(i))
    time.sleep(0.05)
    gui.typewrite(["tab"])
    gui.click(865,345)
    gui.typewrite("hello")
    gui.typewrite(["enter"])
    gui.typewrite("(shut up)")
    gui.moveTo(865,665)
    gui.click()
    time.sleep(0.5)
    #changeLanguage()
'''gui.moveTo(145,180)
gui.click()
time.sleep(0.1)
gui.typewrite("rui pv")
time.sleep(0.1)
gui.moveTo(106,302)
for i in range(1,10):
    gui.click()
    time.sleep(0.3)
    gui.moveTo(520,696)
    gui.click()
    gui.typewrite("fprv")'''
'''printLocation = [500,685]
time.sleep(5)
gui.moveTo(89,256)
gui.click()
time.sleep(1)
gui.moveTo(printLocation)  
gui.click()
gui.typewrite("Yotam is not so good as he thinks")
gui.typewrite(["enter"])'''
'''gui.click(520,685)
time.sleep(1)
for i in range(1000):
    gui.typewrite("kapara")
    gui.typewrite(["enter"])
    time.sleep(0.05)'''